* First import previous table from R:

In [4]:
import pandas as pd
import os

R_table = "/cluster/db/mecoulter/RNAseq2/RNAquant_analysis_result/all_3H_genes_expressed.csv"
variant_table = "/cluster/db/mecoulter/RNAseq2/high_impact_variant_annotation.csv"

table = pd.read_csv(R_table)
table = table.rename(columns={"BaRTv2 gene": "Genes"})
table.head()

,Unnamed: 0,Genes,Chromosome,Start,End,Pannzer annotation,Coding potentiality
0,1,BaRT2v18chr3HG122920,chr3H,33237821,33244461,tRNA pseudouridine synthase,Coding;Coding;Coding;Coding;Coding;Unproductiv...
1,2,BaRT2v18chr3HG122970,chr3H,33294773,33299957,Pentatricopeptide repeat-containing protein,Coding;Coding;Coding
2,3,BaRT2v18chr3HG122980,chr3H,33300256,33301691,Usp domain-containing protein;Adenine nucleoti...,Coding
3,4,BaRT2v18chr3HG122990,chr3H,33302620,33306323,NaN,Coding
4,5,BaRT2v18chr3HG123000,chr3H,33574180,33580981,SUPPRESSOR OF ABI3-5 isoform X1;OCRE domain-co...,Unproductive;Unproductive;Unproductive;Unprodu...

In [2]:
table2 = pd.read_csv(variant_table)

table2.head()

,Unnamed: 0,Genes,Variant annotation
0,0,BaRT2v18chr3HG122610,splice_acceptor_variant&intron_variant : 31205...
1,1,BaRT2v18chr3HG122620,"missense_variant : 31213469,missense_variant :..."
2,2,BaRT2v18chr3HG122640,"missense_variant : 31227113,missense_variant :..."
3,3,BaRT2v18chr3HG122680,missense_variant : 31428979
4,4,BaRT2v18chr3HG122690,"missense_variant : 31432599,missense_variant :..."

In [5]:
merged_table = pd.merge(table,table2,how="left", on="Genes")
len(merged_table)
merged_table.head()

,Unnamed: 0_x,Genes,Chromosome,Start,End,Pannzer annotation,Coding potentiality,Unnamed: 0_y,Variant annotation
0,1,BaRT2v18chr3HG122920,chr3H,33237821,33244461,tRNA pseudouridine synthase,Coding;Coding;Coding;Coding;Coding;Unproductiv...,22.0,"missense_variant : 33241825,missense_variant :..."
1,2,BaRT2v18chr3HG122970,chr3H,33294773,33299957,Pentatricopeptide repeat-containing protein,Coding;Coding;Coding,23.0,"missense_variant : 33298503,missense_variant :..."
2,3,BaRT2v18chr3HG122980,chr3H,33300256,33301691,Usp domain-containing protein;Adenine nucleoti...,Coding,NaN,NaN
3,4,BaRT2v18chr3HG122990,chr3H,33302620,33306323,NaN,Coding,24.0,"missense_variant : 33305702,missense_variant :..."
4,5,BaRT2v18chr3HG123000,chr3H,33574180,33580981,SUPPRESSOR OF ABI3-5 isoform X1;OCRE domain-co...,Unproductive;Unproductive;Unproductive;Unprodu...,25.0,"missense_variant : 33577017,missense_variant :..."

In [6]:
len(merged_table)
merged_table.columns

Index(['Unnamed: 0_x', 'Genes', 'Chromosome', 'Start', 'End',
       'Pannzer annotation', 'Coding potentiality', 'Unnamed: 0_y',
       'Variant annotation'],
      dtype='object')

In [7]:
merged_table = merged_table.drop(["Unnamed: 0_x","Unnamed: 0_y"],axis=1)
merged_table.head()

,Genes,Chromosome,Start,End,Pannzer annotation,Coding potentiality,Variant annotation
0,BaRT2v18chr3HG122920,chr3H,33237821,33244461,tRNA pseudouridine synthase,Coding;Coding;Coding;Coding;Coding;Unproductiv...,"missense_variant : 33241825,missense_variant :..."
1,BaRT2v18chr3HG122970,chr3H,33294773,33299957,Pentatricopeptide repeat-containing protein,Coding;Coding;Coding,"missense_variant : 33298503,missense_variant :..."
2,BaRT2v18chr3HG122980,chr3H,33300256,33301691,Usp domain-containing protein;Adenine nucleoti...,Coding,NaN
3,BaRT2v18chr3HG122990,chr3H,33302620,33306323,NaN,Coding,"missense_variant : 33305702,missense_variant :..."
4,BaRT2v18chr3HG123000,chr3H,33574180,33580981,SUPPRESSOR OF ABI3-5 isoform X1;OCRE domain-co...,Unproductive;Unproductive;Unproductive;Unprodu...,"missense_variant : 33577017,missense_variant :..."

In [8]:
merged_table = merged_table.rename(columns={"raw_p": "Raw p", "adj_p": "Adj. p", "function.": "Predicted function", "GO.IDs":"GO ids"})
merged_table.head()

,Genes,Chromosome,Start,End,Pannzer annotation,Coding potentiality,Variant annotation
0,BaRT2v18chr3HG122920,chr3H,33237821,33244461,tRNA pseudouridine synthase,Coding;Coding;Coding;Coding;Coding;Unproductiv...,"missense_variant : 33241825,missense_variant :..."
1,BaRT2v18chr3HG122970,chr3H,33294773,33299957,Pentatricopeptide repeat-containing protein,Coding;Coding;Coding,"missense_variant : 33298503,missense_variant :..."
2,BaRT2v18chr3HG122980,chr3H,33300256,33301691,Usp domain-containing protein;Adenine nucleoti...,Coding,NaN
3,BaRT2v18chr3HG122990,chr3H,33302620,33306323,NaN,Coding,"missense_variant : 33305702,missense_variant :..."
4,BaRT2v18chr3HG123000,chr3H,33574180,33580981,SUPPRESSOR OF ABI3-5 isoform X1;OCRE domain-co...,Unproductive;Unproductive;Unproductive;Unprodu...,"missense_variant : 33577017,missense_variant :..."

In [10]:
#Write to file
#merged_table = merged_table.drop(["GO ids"],axis=1)#Drop this for now, too many values
merged_table.to_csv(path_or_buf="/cluster/db/mecoulter/RNAseq2/RNAseq_variant_candidates_experiment2only.csv",header=True)